dist: trusty
sudo: true
language: java
services:
  - docker
jdk:
  - oraclejdk11
before_install:
  - chmod +x mvnw
cache:
  directories:
    - "$HOME/.m2/repository"
script:
  - java --version
  - ./mvnw clean install
  - sudo ./mvnw package
  - sudo docker build -f src/main/docker/Dockerfile.jvm -t quarkus/backend-jvm .
  - sudo ./mvnw test
notifications:
  email:
    recipients:
      - mehdi.seddiki@epita.fr
    on_success: change
    on_failure: always
