language: java
services:
  - docker
jdk:
  - oraclejdk11
script:
  ./mvnw -Dquarkus-profile=test test
notifications:
  email:
    recipients:
      - mehdi.seddiki@epita.fr
    on_success: change
    on_failure: always

