dist: trusty
sudo: true
language: java
services:
  - docker
  - postgresql
before_script:
  - psql -c 'create database plic;' -U postgres
  - cp src/main/resources/application.properties.travis src/main/resources/application.properties
jdk:
  - oraclejdk11
before_install:
  - chmod +x mvnw
cache:
  directories:
    - "$HOME/.m2/repository"
script:
  - sudo ./mvnw package -DskipTests
  - sudo docker build -f src/main/docker/Dockerfile.jvm -t quarkus/backend-jvm .
  - sudo ./mvnw -Dquarkus-profile=test test
notifications:
  email:
    recipients:
      - mehdi.seddiki@epita.fr
    on_success: change
    on_failure: always
