language: java
git:
  depth: 1
branches:
  only:
    - gh-pages
    - /.*/
services:
  - docker
jdk:
  - oraclejdk11
script:
  sudo ./mvnw package
  sudo docker build -f src/main/docker/Dockerfile.jvm -t quarkus/backend-jvm .
notifications:
  email:
    recipients:
      - mehdi.seddiki@epita.fr
    on_success: change
    on_failure: always

